version: "3.8"

services:
  lapvision-server-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIGURATION: Debug
    container_name: lapvision-server-dev
    ports:
      - "5082:5082"
      - "7234:7234"
      - "5223:5223"
      - "7222:7222"