version: "3.8"

services:
  api:
    build:
      context: ./API  # Set context to the API project
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - app

  app:
    build:
      context: ./App  # Set context to the App project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"